img_edel1 = "https://i.imgur.com/YiRNACH.png" # 에델슈타인 
img_edel2 = "https://i.imgur.com/SDaaCJk.png" # 에델슈타인
img_edel3 = "https://i.imgur.com/8QxQVeP.png" # 에델슈타인
img_edel4 = "https://i.imgur.com/qToH4KQ.png" # 에델슈타인
img_edel5 = "https://i.imgur.com/J7A6nQg.png" # 에델슈타인
img_edel6 = "https://i.imgur.com/YMDhiGp.png" # 에델슈타인
img_edel7 = "https://i.imgur.com/jLrZBUG.png" # 에델슈타인
img_edel8 = "https://i.imgur.com/D5jxOc9.png" # 에델슈타인
img_edel9 = "https://i.imgur.com/3bDFreT.png" # 에델슈타인
img_edel10 = "https://i.imgur.com/8PBqgzz.png" # 에델슈타인
img_edel11 = "https://i.imgur.com/1rtfBO0.png" # 에델슈타인
img_edel12 = "https://i.imgur.com/MnsIg0o.png" # 에델슈타인
img_edel13 = "https://i.imgur.com/WOUGlqN.png" # 에델슈타인

img_nihal1 = 'https://i.imgur.com/lQEaHw4.png' # 니할사막 흰 모래토끼
img_nihal2 = 'https://i.imgur.com/qV6ZctU.png' # 니할사막 갈색 모래토끼
img_nihal3 = 'https://i.imgur.com/mW1lIt2.png' # 니할사막 귀마개 프릴드
img_nihal4 = 'https://i.imgur.com/dbxSxE9.png' # 니할사막 목도리 프릴드
img_nihal5 = 'https://i.imgur.com/GAKWtes.png' # 니할사막 주니어 카투스
img_nihal6 = 'https://i.imgur.com/sQncfX5.png' # 니할사막 카투스
img_nihal7 = 'https://i.imgur.com/jArAZN0.png' # 니할사막 로얄 카투스
img_nihal8 = 'https://i.imgur.com/b0Ntq1t.png' # 니할사막 벨라모아
img_nihal9 = 'https://i.imgur.com/pXkurX4.png' # 니할사막 미요캐츠
img_nihal10 = 'https://i.imgur.com/RvwdIPD.png' # 니할사막 키요
img_nihal11 = 'https://i.imgur.com/sNd0qW3.png' # 니할사막 모래난쟁이
img_nihal12 = 'https://i.imgur.com/W9vRsZa.png' # 니할사막 모래거인
img_nihal13 = 'https://i.imgur.com/uQFxSmX.png' # 니할사막 스콜피언
img_nihal14 = 'https://i.imgur.com/zYmHzPM.png' # 니할사막 모래 두더지
img_nihal15 = 'https://i.imgur.com/JWAyRjh.png' # 니할사막 붉은 모래난쟁이
img_nihal16 = 'https://i.imgur.com/wEwBqCc.png' # 니할사막 큐브슬라임
img_nihal17 = 'https://i.imgur.com/ID5FyIZ.png' # 니할사막 루모
img_nihal18 = 'https://i.imgur.com/0PSUvKt.png' # 니할사막 트리플 루모
img_nihal19 = 'https://i.imgur.com/wz1a8rh.png' # 니할사막 호문
img_nihal20 = 'https://i.imgur.com/gDhVdAI.png' # 니할사막 호문쿨루
img_nihal21 = 'https://i.imgur.com/WBngJLz.png' # 니할사막 호문스큘러
img_nihal22 = 'https://i.imgur.com/kllOe2k.png' # 니할사막 아이언 뮤테
img_nihal23 = 'https://i.imgur.com/4INzIPg.png' # 니할사막 강화된 아이언 뮤테
img_nihal24 = 'https://i.imgur.com/ih2NfeM.png' # 니할사막 미스릴 뮤테
img_nihal25 = 'https://i.imgur.com/CoaOj4I.png' # 니할사막 강화된 미스릴 뮤테
img_nihal26 = 'https://i.imgur.com/fQYV8uy.png' # 니할사막 사이티
img_nihal27 = 'https://i.imgur.com/N1xy5WM.png' # 니할사막 로이드
img_nihal28 = 'https://i.imgur.com/3ivRRDW.png' # 니할사막 네오 휴로이드
img_nihal29 = 'https://i.imgur.com/X26liZe.png' # 니할사막 D.로이
img_nihal30 = 'https://i.imgur.com/foJE8bx.png' # 니할사막 자동경비시스템
img_nihal31 = 'https://i.imgur.com/S8Ssxbh.png' # 니할사막 데우 ( 보스 )
img_nihal32 = 'https://i.imgur.com/D9PIwSS.png' # 니할사막 데우 ( 히든보스 )
img_nihal33 = 'https://i.imgur.com/13lJmal.png' # 니할사막 루루모 ( 보스 )
img_nihal34 = 'https://i.imgur.com/CC2unnQ.png' # 니할사막 루루모모 ( 히든보스 )
img_nihal35 = 'https://i.imgur.com/MBpvGpK.png' # 니할사막 호문스페큘러 ( 보스 )
img_nihal36 = 'https://i.imgur.com/nK1ZZpc.png' # 니할사막 디트와 로이 ( 보스 )
img_nihal37 = 'https://i.imgur.com/HJjfQPH.png' # 니할사막 키메라 ( 보스 )
img_nihal38 = 'https://i.imgur.com/2RyP1GH.png' # 니할사막 키메라 ( 히든보스 )
img_nihal39 = 'https://i.imgur.com/0g3KTZR.png' # 니할사막 프랑켄로이드 ( 보스 )
img_nihal40 = 'https://i.imgur.com/rGLst8Z.png' # 니할사막 화난 프랑켄로이드 ( 히든보스 )


img_leben1 = "https://i.imgur.com/tc9S71j.png" # 레벤 광산 경비로봇
img_leben2 = "https://i.imgur.com/09rLXAx.png" # 레벤 광산 경비로봇L
img_leben3 = "https://i.imgur.com/uA93Gmn.png" # 레벤 광산 빅 스파이더
img_leben4 = "https://i.imgur.com/o64pGkS.png" # 레벤 광산 카트베어
img_leben5 = "https://i.imgur.com/kP1GtoI.png" # 레벤 광산 라키
img_leben6 = "https://i.imgur.com/HO5igg2.png" # 레벤 광산 라쿤
img_leben7 = "https://i.imgur.com/ROECrhT.png" # 레벤 광산 라칸
img_leben8 = "https://i.imgur.com/7V0bFLD.png" # 레벤 광산 방어 시스템
img_leben9 = "https://i.imgur.com/YIP5ztP.png" # 레벤 광산 강화된 방어 시스템
img_leben10 = "https://i.imgur.com/Q89HItY.png" # 레벤 광산 AF형 안드로이드
img_leben11 = "https://i.imgur.com/KIRK5OQ.png" # 레벤 광산 고장난 DF형 안드로이드
img_leben12 = "https://i.imgur.com/0yNInhk.png" # 레벤 광산 광석 이터


img_aquaroad1 = "https://i.imgur.com/3egbQOP.png" # 아쿠아로드 씨클
img_aquaroad2 = "https://i.imgur.com/zdr0V7U.png" # 아쿠아로드 씨코
img_aquaroad3 = "https://i.imgur.com/3iuAqYY.png" # 아쿠아로드 스쿠버 페페
img_aquaroad4 = "https://i.imgur.com/6pe135w.png" # 아쿠아로드 주니어 씰
img_aquaroad5 = "https://i.imgur.com/3I91Fgj.png" # 아쿠아로드 핀붐
img_aquaroad6 = "https://i.imgur.com/xlPxR0Z.png" # 아쿠아로드 버블피쉬
img_aquaroad7 = "https://i.imgur.com/P8YZXKV.png" # 아쿠아로드 플라워 피쉬
img_aquaroad8 = "https://i.imgur.com/7jNYleF.png" # 아쿠아로드 마스크 피쉬
img_aquaroad9 = "https://i.imgur.com/aMEwfP5.png" # 아쿠아로드 푸퍼
img_aquaroad10 = "https://i.imgur.com/UwSiwg8.png" # 아쿠아로드 포이즌 푸퍼
img_aquaroad11 = "https://i.imgur.com/T3fMGlT.png" # 아쿠아로드 크라피
img_aquaroad12 = "https://i.imgur.com/CVEAlu6.png" # 아쿠아로드 크립
img_aquaroad13 = "https://i.imgur.com/HufmeoS.png" # 아쿠아로드 스파커
img_aquaroad14 = "https://i.imgur.com/ItbwpAQ.png" # 아쿠아로드 프리져
img_aquaroad15 = "https://i.imgur.com/eMESodk.png" # 아쿠아로드 폭렬 망둥이집
img_aquaroad16 = "https://i.imgur.com/bbQSufJ.png" # 아쿠아로드 망둥이
img_aquaroad17 = "https://i.imgur.com/2SyqPmA.png" # 아쿠아로드 본 피쉬
img_aquaroad18 = "https://i.imgur.com/6vBdlBO.png" # 아쿠아로드 스퀴드
img_aquaroad19 = "https://i.imgur.com/Iqb11RK.png" # 아쿠아로드 리셀 스퀴드
img_aquaroad20 = "https://i.imgur.com/GeuFHG0.png" # 아쿠아로드 샤크
img_aquaroad21 = "https://i.imgur.com/yHrj32P.png" # 아쿠아로드 콜드샤크
img_aquaroad22 = "https://i.imgur.com/ck9OnQS.png" # 아쿠아로드 블러드붐
img_aquaroad23 = "https://i.imgur.com/nieYZvC.png" # 아쿠아로드 세르프 ( 보스 )
img_aquaroad24 = "https://i.imgur.com/xRiY3Ce.png" # 아쿠아로드 피아누스 ( 보스 )


img_orbis1 = "https://i.imgur.com/3z52USa.png" # 오르비스 스톤볼
img_orbis2 = "https://i.imgur.com/TSuat1N.png" # 오르비스 아이스 스톤볼
img_orbis3 = "https://i.imgur.com/khsVBxG.png" # 오르비스 파이어 스톤볼
img_orbis4 = "https://i.imgur.com/adq9edw.png" # 오르비스 샐리온
img_orbis5 = "https://i.imgur.com/lN7ZFY8.png" # 오르비스 라이오너
img_orbis6 = "https://i.imgur.com/FfTyvQb.png" # 오르비스 그류핀
img_orbis7 = "https://i.imgur.com/dm4jscM.png" # 오르비스 루이넬
img_orbis8 = "https://i.imgur.com/FyzkQ1F.png" # 오르비스 루나픽시
img_orbis9 = "https://i.imgur.com/0vtamPk.png" # 오르비스 스타픽시
img_orbis10 = "https://i.imgur.com/ICqqBtM.png" # 오르비스 러스터픽시
img_orbis11 = "https://i.imgur.com/LIno6hR.png" # 오르비스 고스트픽시
img_orbis12 = "https://i.imgur.com/hMGfCSz.png" # 오르비스 네펜데스
img_orbis13 = "https://i.imgur.com/r95Dmvu.png" # 오르비스 다크 네펜데스
img_orbis14 = "https://i.imgur.com/qRBrmmI.png" # 오르비스 골든 스코피
img_orbis15 = "https://i.imgur.com/ElX2naY.png" # 오르비스 골든 맘무트
img_orbis16 = "https://i.imgur.com/U1PCxAO.png" # 오르비스 크림슨 발록 ( 보스 )
img_orbis17 = "https://i.imgur.com/kDQAeVZ.png" # 오르비스 엘리쟈 ( 보스 )
img_orbis18 = "https://i.imgur.com/NJ2WwnO.png" # 오르비스 파파픽시 ( 보스 )
img_orbis19 = "https://i.imgur.com/2Z4R1hP.png" # 오르비스 크세르크세스 ( 보스 )

img_elnath1 = "https://i.imgur.com/QICr45o.png" # 엘나스 주니어 예티
img_elnath2 = "https://i.imgur.com/YcyYjro.png" # 엘나스 다크 주니어 예티
img_elnath3 = "https://i.imgur.com/11hzhhn.png" # 엘나스 화이트팽
img_elnath4 = "https://i.imgur.com/cW00sbf.png" # 엘나스 헥터
img_elnath5 = "https://i.imgur.com/6JZAvhx.png" # 엘나스 페페
img_elnath6 = "https://i.imgur.com/lE0QiIN.png" # 엘나스 다크 페페
img_elnath7 = "https://i.imgur.com/RsncqZQ.png" # 엘나스 예티
img_elnath8 = "https://i.imgur.com/AzENFYy.png" # 엘나스 다크 예티
img_elnath9 = "https://i.imgur.com/bc61xQI.png" # 엘나스 예티와 페페
img_elnath10 = "https://i.imgur.com/BJ5zE2j.png" # 엘나스 다크 예티와 페페
img_elnath11 = "https://i.imgur.com/QebHVro.png" # 엘나스 웨어울프
img_elnath12 = "https://i.imgur.com/wCvOmde.png" # 엘나스 라이칸스로프
img_elnath13 = "https://i.imgur.com/gJgQPXO.png" # 엘나스 호브 헥터
img_elnath14 = "https://i.imgur.com/7cd1Xj9.png" # 엘나스 정예 호브
img_elnath15 = "https://i.imgur.com/2GjjEIB.png" # 엘나스 컴뱃 호브
img_elnath16 = "https://i.imgur.com/8zJV4kE.png" # 엘나스 컴뱃 호브
img_elnath17 = "https://i.imgur.com/oXhEatg.png" # 엘나스 설산의 마녀 ( 보스 )
img_elnath18 = "https://i.imgur.com/z6AeoNv.png" # 엘나스 스노우맨 ( 보스 )
img_elnath19 = "https://i.imgur.com/MvzLNpd.png" # 엘나스 리치 ( 보스 )
img_elnath20 = "https://i.imgur.com/SlqV45i.png" # 엘나스 렉스 ( 보스 )


img_luduslake1 = "https://i.imgur.com/kugUjzs.png" # 루더스 호수 북치는토끼
img_luduslake2 = "https://i.imgur.com/YXLxpj0.png" # 루더스 호수 브라운테니
img_luduslake3 = "https://i.imgur.com/qJSGrnn.png" # 루더스 호수 핑크테니
img_luduslake4 = "https://i.imgur.com/LPFhyjj.png" # 루더스 호수 팬더테니
img_luduslake5 = "https://i.imgur.com/QS4u9Lp.png" # 루더스 호수 더키 패밀리
img_luduslake6 = "https://i.imgur.com/TWEVQzE.png" # 루더스 호수 치크세이버
img_luduslake7 = "https://i.imgur.com/pyPCHS2.png" # 루더스 호수 핑크세이버
img_luduslake8 = "https://i.imgur.com/k1J2Mu6.png" # 루더스 호수 스카이세이버
img_luduslake9 = "https://i.imgur.com/nM1yC6W.png" # 루더스 호수 처프
img_luduslake10 = "https://i.imgur.com/iCBAhZC.png" # 루더스 호수 트위터
img_luduslake11 = "https://i.imgur.com/Mdz8v7E.png" # 루더스 호수 블록퍼스
img_luduslake12 = "https://i.imgur.com/cgFa0O8.png" # 루더스 호수 킹 블록퍼스
img_luduslake13 = "https://i.imgur.com/SPvZ4qT.png" # 루더스 호수 블록골렘
img_luduslake14 = "https://i.imgur.com/eZRh88b.png" # 루더스 호수 킹 블록골렘
img_luduslake15 = "https://i.imgur.com/ICEauyn.png" # 루더스 호수 라츠
img_luduslake16 = "https://i.imgur.com/WtcsTcr.png" # 루더스 호수 블랙 라츠
img_luduslake17 = "https://i.imgur.com/Ae8TIXp.png" # 루더스 호수 장난감 목마
img_luduslake18 = "https://i.imgur.com/SDTLo7T.png" # 루더스 호수 로보토이
img_luduslake19 = "https://i.imgur.com/8S4G3Nd.png" # 루더스 호수 마스터 로보
img_luduslake20 = "https://i.imgur.com/ZWGUD1n.png" # 루더스 호수 롬바드 ( 보스 )
img_luduslake21 = "https://i.imgur.com/TtHu8n5.png" # 루더스 호수 타이머 ( 보스 )


img_ereb1 = "https://i.imgur.com/D6R5Sav.png" # 에레브 티노
img_ereb2 = "https://i.imgur.com/uLHMDPO.png" # 에레브 티브
img_ereb3 = "https://i.imgur.com/rb5yMVL.png" # 에레브 티무
img_ereb4 = "https://i.imgur.com/nIRjqBE.png" # 에레브 티루
img_ereb5 = "https://i.imgur.com/irRl6DR.png" # 에레브 티구르


img_temple1 = 'https://i.imgur.com/tGMQLIN.png' # 시간의신전 시간의 눈
img_temple2 = 'https://i.imgur.com/Rhc9x9X.png' # 시간의신전 추억의 사제
img_temple3 = 'https://i.imgur.com/Z0KYZsB.png' # 시간의신전 추억의 신관
img_temple4 = 'https://i.imgur.com/f16scUU.png' # 시간의신전 추억의 수호병
img_temple5 = 'https://i.imgur.com/ujHSrEP.png' # 시간의신전 추억의 수호대장
img_temple6 = 'https://i.imgur.com/9YkMVue.png' # 시간의신전 후회의 사제
img_temple7 = 'https://i.imgur.com/xBuZuVP.png' # 시간의신전 후회의 신관
img_temple8 = 'https://i.imgur.com/QrB8DbE.png' # 시간의신전 후회의 수호병
img_temple9 = 'https://i.imgur.com/4YFDAYg.png' # 시간의신전 후회의 수호대장
img_temple10 = 'https://i.imgur.com/KJApxj7.png' # 시간의신전 망각의 사제
img_temple11 = 'https://i.imgur.com/A9tbf7m.png' # 시간의신전 망각의 신관
img_temple12 = 'https://i.imgur.com/9KKGGSi.png' # 시간의신전 망각의 수호병
img_temple13 = 'https://i.imgur.com/to0Zbnb.png' # 시간의신전 망각의 수호대장
img_temple14 = 'https://i.imgur.com/4v04sJr.png' # 시간의신전 타락한 시간의 신관
img_temple15 = 'https://i.imgur.com/1gF7fxn.png' # 시간의신전 타락한 시간의 수호대장
img_temple16 = 'https://i.imgur.com/sLEkWdG.png' # 시간의신전 도도 ( 보스 )
img_temple17 = 'https://i.imgur.com/849RZxb.png' # 시간의신전 도도 ( 히든보스 )
img_temple18 = 'https://i.imgur.com/q5eOKBL.png' # 시간의신전 릴리노흐 ( 보스 )
img_temple19 = 'https://i.imgur.com/oBRqR6V.png' # 시간의신전 릴리노흐 ( 히든보스 )
img_temple20 = 'https://i.imgur.com/azD2kFj.png' # 시간의신전 라이카 ( 보스 )
img_temple21 = 'https://i.imgur.com/bUy9c9v.png' # 시간의신전 라이카 ( 히든보스 )


img_rien1 = "https://i.imgur.com/riS4Nrh.png" # 리엔 무루
img_rien2 = "https://i.imgur.com/odjxk2k.png" # 리엔 무루파
img_rien3 = "https://i.imgur.com/gC9MhSl.png" # 리엔 무루피아
img_rien4 = "https://i.imgur.com/FA6eOX3.png" # 리엔 무루무루
img_rien5 = "https://i.imgur.com/rqZFB5W.png" # 리엔 무루쿤


img_minar1 = 'https://i.imgur.com/FxgW7ld.png' # 미나르숲 레쉬
img_minar2 = 'https://i.imgur.com/MbvXi82.png' # 미나르숲 다크 레쉬
img_minar3 = 'https://i.imgur.com/dYB2uFJ.png' # 미나르숲 비틀
img_minar4 = 'https://i.imgur.com/yIhlI65.png' # 미나르숲 듀얼 비틀
img_minar5 = 'https://i.imgur.com/6APPU0p.png' # 미나르숲 호브
img_minar6 = 'https://i.imgur.com/C0l7CnQ.png' # 미나르숲 핀호브
img_minar7 = 'https://i.imgur.com/qDEz1Iz.png' # 미나르숲 가시덤불
img_minar8 = 'https://i.imgur.com/UY7p4ot.png' # 미나르숲 헹키
img_minar9 = 'https://i.imgur.com/UkujFjb.png' # 미나르숲 하프
img_minar10 = 'https://i.imgur.com/PuCE4Ck.png' # 미나르숲 블러드 하프
img_minar11 = 'https://i.imgur.com/tiQ6joE.png' # 미나르숲 버크
img_minar12 = 'https://i.imgur.com/3mDsc8R.png' # 미나르숲 듀얼 버크
img_minar13 = 'https://i.imgur.com/L8lcoXW.png' # 미나르숲 검은 켄타우로스
img_minar14 = 'https://i.imgur.com/LyTuvJs.png' # 미나르숲 붉은 켄타우로스
img_minar15 = 'https://i.imgur.com/iqF5eJo.png' # 미나르숲 푸른 켄타우로스
img_minar16 = 'https://i.imgur.com/tLZCnH0.png' # 미나르숲 블루 드래곤터틀
img_minar17 = 'https://i.imgur.com/LhYp1Hj.png' # 미나르숲 레드 드래곤터틀
img_minar18 = 'https://i.imgur.com/tA9Birw.png' # 미나르숲 리스튼
img_minar19 = 'https://i.imgur.com/w13oQiJ.png' # 미나르숲 브레스튼
img_minar20 = 'https://i.imgur.com/2DMtnje.png' # 미나르숲 그린 코니언
img_minar21 = 'https://i.imgur.com/dLm7RMR.png' # 미나르숲 다크 코니언
img_minar22 = 'https://i.imgur.com/IgIHaQx.png' # 미나르숲 레드 와이번
img_minar23 = 'https://i.imgur.com/hthTWwA.png' # 미나르숲 블루 와이번
img_minar24 = 'https://i.imgur.com/sgxUr0h.png' # 미나르숲 다크 와이번
img_minar25 = 'https://i.imgur.com/QJsPCVR.png' # 미나르숲 뉴트주니어
img_minar26 = 'https://i.imgur.com/MBdGDOU.png' # 미나르숲 네스트골렘
img_minar27 = 'https://i.imgur.com/v15yu8r.png' # 미나르숲 스켈레곤
img_minar28 = 'https://i.imgur.com/0Okm0x2.png' # 미나르숲 스켈로스
img_minar29 = 'https://i.imgur.com/fgjNvLR.png' # 미나르숲 마스터 호브 ( 보스 )
img_minar30 = 'https://i.imgur.com/Mqoep21.png' # 미나르숲 마스터 하프 ( 보스 )
img_minar31 = 'https://i.imgur.com/llWQp15.png' # 미나르숲 마뇽 ( 보스 )
img_minar32 = 'https://i.imgur.com/6EIkCgu.png' # 미나르숲 마뇽 ( 히든보스 )
img_minar33 = 'https://i.imgur.com/3SBe6wx.png' # 미나르숲 그리프 ( 보스 )
img_minar34 = 'https://i.imgur.com/AUzced6.png' # 미나르숲 그리프 ( 히든보스 )
img_minar35 = 'https://i.imgur.com/FjRCCln.png' # 미나르숲 켄타우로스 킹 ( 보스 )
img_minar36 = 'https://i.imgur.com/ZdzMM33.png' # 미나르숲 레비아탄 ( 보스 )
img_minar37 = 'https://i.imgur.com/ZyW4aqt.png' # 미나르숲 레비아탄 ( 히든보스 )
img_minar38 = 'https://i.imgur.com/9OXZryD.png' # 미나르숲 드래고니카 ( 보스 )
img_minar39 = 'https://i.imgur.com/nZcl00A.png' # 미나르숲 드래곤라이더 ( 보스 )


img_vic1 = "https://i.imgur.com/kPMrXUd.png" # 헤네시스
img_vic2 = "https://i.imgur.com/rulZMFu.png" # 헤네시스
img_vic3 = "https://i.imgur.com/KRirKRL.png" # 헤네시스
img_vic4 = "https://i.imgur.com/t9F7vLq.png" # 헤네시스
img_vic5 = "https://i.imgur.com/hRMea5O.png" # 헤네시스
img_vic6 = "https://i.imgur.com/juU2xlK.png" # 리스항구
img_vic7 = "https://i.imgur.com/eqF4gzs.png" # 리스항구
img_vic8 = "https://i.imgur.com/09NNPRR.png" # 리스항구
img_vic9 = "https://i.imgur.com/RqaQ74P.png" # 엘리니아
img_vic10 = "https://i.imgur.com/y1mNBbP.png" # 엘리니아
img_vic11 = "https://i.imgur.com/pTKhTlh.png" # 엘리니아
img_vic12 = "https://i.imgur.com/sUkuus0.png" # 엘리니아
img_vic13 = "https://i.imgur.com/VliAzgk.png" # 엘리니아
img_vic14 = "https://i.imgur.com/RrP8aaB.png" # 엘리니아
img_vic15 = "https://i.imgur.com/fgmYInj.png" # 엘리니아
img_vic16 = "https://i.imgur.com/a7yZLYx.png" # 엘리니아
img_vic17 = "https://i.imgur.com/UjGctQ1.png" # 헤네시스 스톤골렘
img_vic18 = "https://i.imgur.com/Q28SCS2.png" # 헤네시스 다크 스톤골렘
img_vic19 = "https://i.imgur.com/8mNI0GX.png" # 헤네시스 아이스 믹스골렘
img_vic20 = "https://i.imgur.com/CmAqGVu.png" # 헤네시스 파이어 믹스골렘
img_vic21 = "https://i.imgur.com/CA0EEUl.png" # 페리온 스텀프
img_vic22 = "https://i.imgur.com/JD8t1HN.png" # 페리온 다크 스텀프
img_vic23 = "https://i.imgur.com/qCzrPWp.png" # 페리온 엑스텀프
img_vic24 = "https://i.imgur.com/eHGjq1r.png" # 페리온 다크 엑스텀프
img_vic25 = "https://i.imgur.com/46kiQvm.png" # 페리온 고스텀프
img_vic26 = "https://i.imgur.com/zbPA9cu.png" # 페리온 히죽대는 고스텀프
img_vic27 = "https://i.imgur.com/ttFOOuF.png" # 페리온 우드마스크
img_vic28 = "https://i.imgur.com/JpVNMw8.png" # 페리온 스톤마스크
img_vic29 = "https://i.imgur.com/UOqtWY1.png" # 리스항구 달팽이
img_vic30 = "https://i.imgur.com/hVBDwEn.png" # 리스항구 파란 달팽이
img_vic31 = "https://i.imgur.com/EF7ZoEy.png" # 리스항구 빨간 달팽이
img_vic32 = "https://i.imgur.com/sPhT1p1.png" # 헤네시스 스포아
img_vic33 = "https://i.imgur.com/AcWiYbG.png" # 페리온 스켈독
img_vic34 = "https://i.imgur.com/MXna85g.png" # 페리온 스켈레톤 사병
img_vic35 = "https://i.imgur.com/ufTsx65.png" # 페리온 스켈레톤 장교
img_vic36 = "https://i.imgur.com/9abPx27.png" # 페리온 스켈레톤 지휘관
img_vic41 = "https://i.imgur.com/2yXrmVS.png" # 페리온 스켈레톤 총사령관 ( 보스 )
img_vic37 = "https://i.imgur.com/Ts3z4VH.png" # 헤네시스 머쉬맘 ( 보스 )
img_vic38 = "https://i.imgur.com/PUJDWuN.png" # 헤네시스 블루 머쉬맘 ( 보스 )
img_vic39 = "https://i.imgur.com/JpVNMw8.png" # 페리온 스텀피 ( 보스 )
img_vic40 = "https://i.imgur.com/dLBkdaL.png" # 헤네시스 마노 ( 보스 )


img_slp1 = "https://i.imgur.com/xgevjxy.png" # 슬리피우드 카파 드레이크
img_slp2 = "https://i.imgur.com/1MTJPX6.gif" # 슬리피우드 드레이크
img_slp3 = "https://i.imgur.com/AL2DNYm.gif" # 슬리피우드 레드 드레이크
img_slp4 = "https://i.imgur.com/m609GYu.gif" # 슬리피우드 아이스 드레이크
img_slp5 = "https://i.imgur.com/W5SUJJj.gif" # 슬리피우드 다크 드레이크
img_slp6 = "https://i.imgur.com/guPQqbM.gif" # 슬리피우드 와일드카고
img_slp7 = "https://i.imgur.com/s96YnR3.png" # 슬리피우드 타우로마시스
img_slp8 = "https://i.imgur.com/f6yPbZD.png" # 슬리피우드 타우로스피어
img_slp9 = "https://i.imgur.com/CvyM0xb.png" # 슬리피우드 좀비버섯
img_slp10 = "https://i.imgur.com/giTXZ0h.gif" # 슬리피우드 주니어 발록 ( 보스 ) 
img_slp11 = "https://i.imgur.com/g8IueLe.png" # 슬리피우드 좀비머쉬맘 ( 보스 )

img_folk1 = "https://i.imgur.com/6AFX3cF.png" # 아랫마을 삼미호
img_folk2 = "https://i.imgur.com/bmLmm8i.png" # 아랫마을 월묘
img_folk3 = "https://i.imgur.com/9IQLDSV.png" # 아랫마을 호돌이
img_folk4 = "https://i.imgur.com/gecNLiC.png" # 아랫마을 호걸
img_folk5 = "https://i.imgur.com/6ztbaDL.png" # 아랫마을 파란 왕도깨비
img_folk6 = "https://i.imgur.com/ObFEcUJ.png" # 아랫마을 초록 왕도깨비
img_folk7 = "https://i.imgur.com/Ew8tQlw.png" # 아랫마을 노란 왕도깨비


img_deepmine1 = "https://i.imgur.com/os1Az2i.png" # 폐광 플라이아이
img_deepmine2 = "https://i.imgur.com/PBiczYv.png" # 폐광 쿨리 좀비
img_deepmine3 = "https://i.imgur.com/8s1YLrD.png" # 폐광 마이너좀비
img_deepmine4 = "https://i.imgur.com/iEhdxnc.png" # 폐광 불독
img_deepmine5 = "https://i.imgur.com/JaFyEDq.png" # 폐광 파이어독


img_lioncastle1 = "https://i.imgur.com/gmrZaRz.png" # 사자왕의 성 문지기 크로키
img_lioncastle2 = "https://i.imgur.com/gQaunf2.png" # 사자왕의 성 레인디어
img_lioncastle3 = "https://i.imgur.com/IwCu01N.png" # 사자왕의 성 블러드 레인디어
img_lioncastle4 = "https://i.imgur.com/cdFf25o.png" # 사자왕의 성 베어울프
img_lioncastle5 = "https://i.imgur.com/E3DH5I2.png" # 사자왕의 성 그레이 벌쳐
img_lioncastle6 = "https://i.imgur.com/ePIS0KN.png" # 사자왕의 성 황금벌
img_lioncastle7 = "https://i.imgur.com/GJhTbSF.png" # 사자왕의 성 프로즌 로즈
img_lioncastle8 = "https://i.imgur.com/LnmOHWQ.png" # 사자왕의 성 가든 골렘
img_lioncastle9 = "https://i.imgur.com/rxXjWoe.png" # 사자왕의 성 캐슬 골렘
img_lioncastle10 = "https://i.imgur.com/wmzp9HW.png" # 사자왕의 성 킹 캐슬 골렘 ( 보스 )
img_lioncastle11 = "https://i.imgur.com/r4qBPdK.png" # 사자왕의 성 교도관 아니 ( 보스 )


img_clocktower1 = "https://i.imgur.com/4nRKSF8.png" # 시계탑 최하층 티키
img_clocktower2 = "https://i.imgur.com/Ki99M6i.png" # 시계탑 최하층 틱톡
img_clocktower3 = "https://i.imgur.com/dGN6meT.png" # 시계탑 최하층 크로노스
img_clocktower4 = "https://i.imgur.com/ebx3BNY.png" # 시계탑 최하층 플래툰 크로노스
img_clocktower5 = "https://i.imgur.com/3wJInr5.png" # 시계탑 최하층 마스터 크로노스
img_clocktower6 = "https://i.imgur.com/kydCnsn.png" # 시계탑 최하층 버피
img_clocktower7 = "https://i.imgur.com/2vSIheQ.png" # 시계탑 최하층 레이지 버피
img_clocktower8 = "https://i.imgur.com/EEsKrkW.png" # 시계탑 최하층 버푼
img_clocktower9 = "https://i.imgur.com/462iVp6.png" # 시계탑 최하층 딥 버푼
img_clocktower10 = "https://i.imgur.com/C260stz.png" # 시계탑 최하층 소울테니
img_clocktower11 = "https://i.imgur.com/GBkn21c.png" # 시계탑 최하층 마스터 소울테니
img_clocktower12 = "https://i.imgur.com/8uKjt8k.png" # 시계탑 최하층 데스테니
img_clocktower13 = "https://i.imgur.com/gj99NUE.png" # 시계탑 최하층 마스터 데스테니
img_clocktower14 = "https://i.imgur.com/dd186Lm.png" # 시계탑 최하층 파이렛
img_clocktower15 = "https://i.imgur.com/8eeXxIS.png" # 시계탑 최하층 듀얼 파이렛
img_clocktower16 = "https://i.imgur.com/VMOQu5l.png" # 시계탑 최하층 바이킹
img_clocktower17 = "https://i.imgur.com/0FJHeRB.png" # 시계탑 최하층 기간틱 바이킹
img_clocktower18 = "https://i.imgur.com/Lz2jSyz.png" # 시계탑 최하층 클라크
img_clocktower19 = "https://i.imgur.com/37EYcPt.png" # 시계탑 최하층 다크 클라크
img_clocktower20 = "https://i.imgur.com/3vjdEbw.png" # 시계탑 최하층 팬텀워치
img_clocktower21 = "https://i.imgur.com/wQDADWN.png" # 시계탑 최하층 G.팬텀워치
img_clocktower22 = "https://i.imgur.com/cfCLOEk.png" # 시계탑 최하층 게이트키퍼
img_clocktower23 = "https://i.imgur.com/rSBVRSI.png" # 시계탑 최하층 타나토스
img_clocktower24 = "https://i.imgur.com/JwrM78E.png" # 시계탑 최하층 알리샤르 ( 보스 )


img_riena1 = "https://i.imgur.com/orOAiMJ.png" # 리에나 해협 암모나이트 화석
img_riena2 = "https://i.imgur.com/CUVo4iY.png" # 리에나 해협 물고기 화석
img_riena3 = "https://i.imgur.com/rnB2tM0.png" # 리에나 해협 찐득한 오염물
img_riena4 = "https://i.imgur.com/tDg1CFR.png" # 리에나 해협 찐득한 폐기물
img_riena5 = "https://i.imgur.com/aH9fttC.png" # 리에나 해협 수상한 물개
img_riena6 = "https://i.imgur.com/JtmcZsl.png" # 리에나 해협 수상한 바다표범
img_riena7 = "https://i.imgur.com/SEhrMqG.png" # 리에나 해협 이동형 난로
img_riena8 = "https://i.imgur.com/sdwMZrg.png" # 리에나 해협 이동형 쇄빙기


img_elinel1 = "https://i.imgur.com/YVKKGsi.png" # 엘리넬 반딧불 슬라임
img_elinel2 = "https://i.imgur.com/tSnZecW.png" # 엘리넬 페어리 슬라임
img_elinel3 = "https://i.imgur.com/o1wX0Rh.png" # 엘리넬 미스틱 위습
img_elinel4 = "https://i.imgur.com/HYgnZFO.png" # 엘리넬 워터 엘리먼트
img_elinel5 = "https://i.imgur.com/OUc6sqN.png" # 엘리넬 트리 엘리먼트
img_elinel6 = "https://i.imgur.com/wtP7rcp.png" # 엘리넬 하급 마법책
img_elinel7 = "https://i.imgur.com/lx0cGl0.png" # 엘리넬 상급 마법책
img_elinel8 = "https://i.imgur.com/Qvxmwlb.png" # 엘리넬 양파라고라
img_elinel9 = "https://i.imgur.com/XDbebWg.png" # 엘리넬 순무라고라
img_elinel10 = "https://i.imgur.com/IuqkER7.png" # 엘리넬 몰 킹 ( 보스 )


img_goldbeach1 = "https://i.imgur.com/4T99Pgw.png" # 골드비치 야자수 슬라임
img_goldbeach2 = "https://i.imgur.com/0r9VwGe.png" # 골드비치 코코넛 슬라임
img_goldbeach3 = "https://i.imgur.com/SlfqfKS.png" # 골드비치 초록조개 슬라임
img_goldbeach4 = "https://i.imgur.com/lMyjYLG.png" # 골드비치 보라조개 슬라임
img_goldbeach5 = "https://i.imgur.com/RyQSiki.png" # 골드비치 갈매기 슬라임
img_goldbeach6 = "https://i.imgur.com/tQrD3ZY.png" # 골드비치 빨간 튜브 슬라임
img_goldbeach7 = "https://i.imgur.com/gYPrLl0.png" # 골드비치 파란 튜브 슬라임
img_goldbeach8 = "https://i.imgur.com/Y11H84Q.png" # 골드비치 새우 슬라임
img_goldbeach9 = "https://i.imgur.com/FDnqu7R.png" # 골드비치 날치 슬라임
img_goldbeach10 = "https://i.imgur.com/bqpm5v2.png" # 골드비치 불가사리 문어 슬라임
img_goldbeach11 = "https://i.imgur.com/D5Ne13D.png" # 골드비치 소라문어 슬라임
img_goldbeach12 = "https://i.imgur.com/bTiqSKI.png" # 골드비치 캡틴 블랙 슬라임 ( 보스 )


img_elodin1 = "https://i.imgur.com/Dlg1YSO.png" # 엘로딘
img_elodin2 = "https://i.imgur.com/9qiICXE.png" # 엘로딘
img_elodin3 = "https://i.imgur.com/UvnrYjw.png" # 엘로딘
img_elodin4 = "https://i.imgur.com/HanUPZA.png" # 엘로딘
img_elodin5 = "https://i.imgur.com/yMwkq52.png" # 엘로딘
img_elodin6 = "https://i.imgur.com/htQccFU.png" # 엘로딘
img_elodin7 = "https://i.imgur.com/PXcPJJp.png" # 엘로딘
img_elodin8 = "https://i.imgur.com/B6no0oU.png" # 엘로딘
img_elodin9 = "https://i.imgur.com/3Tzfa9K.png" # 엘로딘
img_elodin10 = "https://i.imgur.com/hhDj3dg.png" # 엘로딘


img_mushroom1 = "https://i.imgur.com/kS7PPp7.png" # 버섯의성 버섯 샹들리에
img_mushroom2 = "https://i.imgur.com/mhLz3oQ.png" # 버섯의성 버섯 철갑옷
img_mushroom3 = "https://i.imgur.com/KKahxZ4.png" # 버섯의성 노곤한 바이킹
img_mushroom4 = "https://i.imgur.com/U2nkPpK.png" # 버섯의성 피곤한 바이킹
img_mushroom5 = "https://i.imgur.com/iPAafK1.png" # 버섯의성 푸근한 바이킹
img_mushroom6 = "https://i.imgur.com/zESacOM.png" # 버섯의성 넉넉한 바이킹
img_mushroom7 = "https://i.imgur.com/l08a9G5.png" # 버섯의성 근엄한 바이킹
img_mushroom8 = "https://i.imgur.com/31PxAsU.png" # 버섯의성 진지한 바이킹
img_mushroom9 = "https://i.imgur.com/TTNBZHD.png" # 버섯의성 오징어 노예간수
img_mushroom10 = "https://i.imgur.com/EO8mArf.png" # 버섯의성 바이킹 군단
img_mushroom11 = "https://i.imgur.com/htP33is.png" # 버섯의성 검은 바이킹 ( 보스 )
img_mushroom12 = "https://i.imgur.com/W0ZU0aE.png" # 버섯의성 총리대신 ( 보스 )